name: Developer Musings
description: A technical blog covering my random thoughts
permalink: /posts/:title/
pygments: true
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
markdown: kramdown
