name: Developer Musings
description: A technical blog covering my random thoughts
permalink: pretty
highlighter: pygments
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
markdown: kramdown

pages_list:
  About: '/about/'
  Archive: '/archive/'
  Feed: '/atom.xml'
