name: Developer Musings
description: A technical blog covering my random thoughts
permalink: pretty
highlighter: rouge
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
markdown: kramdown

kramdown:
  input: GFM
  syntax_highligher: rouge

pages_list:
  About: '/about/'
  Archive: '/archive/'
  Feed: '/atom.xml'

gems: ['jekyll-gist']