# This workflow will do a basic linting of all markdown files

name: 'Github PR CI'

on:
  push:
    tags:
      - "*"
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prettier check
        uses: creyD/prettier_action@v4.3
        with:
          dry: true
          prettier_options: --check **/*.md